---
before:
  hooks:
    - go mod tidy
builds:
  - binary: hugo
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
    ldflags: -s -w -X main.imageVersion={{ if index .Env "VERSION" }}{{ .Env.VERSION }}{{ else }}latest{{ end }}
archives:
  - files:
      - LICENSE
    builds_info:
      group: root
      owner: root
      mode: 0755
    name_template: "dcjulian29.apps.hugo-via-docker_{{ .Version }}_{{ .Os }}"
    format_overrides:
      - format: zip
        goos: windows
nfpms:
  - package_name: dcjulian29.apps.hugo-via-docker
    file_name_template: "{{ .PackageName }}_{{ .Version }}"
    homepage: https://github.com/dcjulian29/docker-hugo/
    maintainer: Julian Easterling <julian@julianscorner.com>
    license: Apache 2.0
    dependencies:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    description: |-
      hugo-via-docker allows the execution of hugo9 binaries via a Docker container.
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/local/bin
    overrides:
      apk:
        dependencies:
          - docker
chocolateys:
  - name: dcjulian29.apps.hugo-via-docker
    authors: Julian Easterling <julian@julianscorner.com>
    project_url: https://github.com/dcjulian29/docker-hugo/
    copyright: 2023 Julian Easterling julian@julianscorner.com
    license_url: https://github.com/dcjulian29/docker-hugo/blob/main/LICENSE
    require_license_acceptance: false
    bug_tracker_url: https://github.com/dcjulian29/docker-hugo/issues
    description: |
      hugo-via-docker allows the execution of hugo9 binaries via a Docker container.
    dependencies:
      - id: docker-desktop
    api_key: "{{ .Env.CHOCO_API_KEY }}"
    source_repo: "https://www.myget.org/F/dcjulian29-chocolatey/"
    skip_publish: false
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
